-- HappyLaundry V113.0.35 Production Safety
create table if not exists public.v113035_audit_log(id bigint generated by default as identity primary key,actor_id uuid default auth.uid(),table_name text not null,record_id text,action text not null,old_data jsonb,new_data jsonb,created_at timestamptz default now());
alter table public.v113035_audit_log enable row level security;
drop policy if exists owner_read_v113035_audit on public.v113035_audit_log;
create policy owner_read_v113035_audit on public.v113035_audit_log for select to authenticated using(exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='owner'));
create or replace function public.v113035_audit_trigger() returns trigger language plpgsql security definer set search_path=public as $$
begin insert into public.v113035_audit_log(table_name,record_id,action,old_data,new_data) values(tg_table_name,coalesce((case when tg_op='DELETE' then to_jsonb(old) else to_jsonb(new) end)->>'id',''),tg_op,case when tg_op in('UPDATE','DELETE') then to_jsonb(old) end,case when tg_op in('INSERT','UPDATE') then to_jsonb(new) end); return case when tg_op='DELETE' then old else new end; end $$;
do $$ declare t text; begin foreach t in array array['v100_orders','v100_payments','v100_cash_entries'] loop if to_regclass('public.'||t) is not null then execute format('drop trigger if exists trg_v113035_audit on public.%I',t); execute format('create trigger trg_v113035_audit after insert or update or delete on public.%I for each row execute function public.v113035_audit_trigger()',t); end if; end loop; end $$;
create table if not exists public.v113035_safety_snapshots(id bigint generated by default as identity primary key,created_by uuid default auth.uid(),label text not null default 'manual',orders jsonb default '[]',payments jsonb default '[]',cash_entries jsonb default '[]',created_at timestamptz default now());
alter table public.v113035_safety_snapshots enable row level security;
drop policy if exists owner_all_v113035_snapshots on public.v113035_safety_snapshots;
create policy owner_all_v113035_snapshots on public.v113035_safety_snapshots for all to authenticated using(exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='owner')) with check(exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='owner'));
create or replace function public.v113035_create_safety_snapshot(p_label text default 'manual') returns bigint language plpgsql security definer set search_path=public as $$
declare v_role text;v_id bigint;vo jsonb:='[]';vp jsonb:='[]';vc jsonb:='[]'; begin select role into v_role from public.profiles where id=auth.uid(); if auth.uid() is null or coalesce(v_role,'')<>'owner' then raise exception 'Hanya Owner yang dapat membuat safety snapshot.'; end if;
if to_regclass('public.v100_orders') is not null then execute 'select coalesce(jsonb_agg(to_jsonb(x)),''[]''::jsonb) from public.v100_orders x' into vo; end if;
if to_regclass('public.v100_payments') is not null then execute 'select coalesce(jsonb_agg(to_jsonb(x)),''[]''::jsonb) from public.v100_payments x' into vp; end if;
if to_regclass('public.v100_cash_entries') is not null then execute 'select coalesce(jsonb_agg(to_jsonb(x)),''[]''::jsonb) from public.v100_cash_entries x' into vc; end if;
insert into public.v113035_safety_snapshots(label,orders,payments,cash_entries) values(coalesce(nullif(trim(p_label),''),'manual'),vo,vp,vc) returning id into v_id; return v_id; end $$;
revoke all on function public.v113035_create_safety_snapshot(text) from public; grant execute on function public.v113035_create_safety_snapshot(text) to authenticated; notify pgrst,'reload schema';
