-- HappyLaundry Enterprise V113.0.63
-- SQL 057 — Quick Progress Produksi + Riwayat Pelaksana
-- Jalankan SEKALI di Supabase SQL Editor SEBELUM deploy V113.0.63.

begin;

alter table public.v100_orders
  add column if not exists progress_last_at timestamptz,
  add column if not exists progress_last_by_name text,
  add column if not exists progress_last_by_login_id text;

-- Order lama: waktu progres awal memakai updated_at/created_at agar reminder tidak kosong.
update public.v100_orders
set progress_last_at = coalesce(progress_last_at, updated_at, created_at)
where progress_last_at is null;

create table if not exists public.v113063_order_progress_history(
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.v100_orders(id) on delete cascade,
  order_no text not null,
  old_status text not null,
  new_status text not null,
  actor_auth_uid uuid null,
  actor_employee_id uuid null references public.v109_users(id) on delete set null,
  actor_name text not null,
  actor_login_id text null,
  created_at timestamptz not null default now()
);

create index if not exists v113063_progress_order_idx
  on public.v113063_order_progress_history(order_id, created_at desc);

alter table public.v113063_order_progress_history enable row level security;

drop policy if exists v113063_progress_history_select on public.v113063_order_progress_history;
create policy v113063_progress_history_select
on public.v113063_order_progress_history
for select to authenticated
using (
  public.v109_is_owner()
  or exists(
    select 1 from public.v109_current_employee() e
    where e.production = true
  )
);

create or replace function public.v113063_update_order_progress(
  p_order_id uuid,
  p_new_status text
)
returns table(
  ok boolean,
  old_status text,
  new_status text,
  actor_name text,
  changed_at timestamptz
)
language plpgsql
security definer
set search_path=public
as $$
declare
  v_order public.v100_orders%rowtype;
  v_owner boolean := false;
  v_employee_id uuid;
  v_actor_name text;
  v_actor_login text;
  v_employee_can_production boolean := false;
  v_changed_at timestamptz := now();
begin
  v_owner := public.v109_is_owner();

  if v_owner then
    select coalesce(nullif(btrim(p.full_name),''),'Owner')
      into v_actor_name
    from public.profiles p
    where p.id = auth.uid()
    limit 1;

    v_actor_name := coalesce(v_actor_name,'Owner');
    v_actor_login := 'OWNER';
  else
    select e.id, e.full_name, e.login_id, e.production
      into v_employee_id, v_actor_name, v_actor_login, v_employee_can_production
    from public.v109_current_employee() e
    limit 1;

    if coalesce(v_employee_can_production,false) = false then
      raise exception 'Akun ini tidak memiliki akses Produksi.';
    end if;
  end if;

  if coalesce(v_actor_name,'') = '' then
    raise exception 'Sesi pengguna tidak dikenali. Silakan login ulang.';
  end if;

  select * into v_order
  from public.v100_orders
  where id = p_order_id
  for update;

  if not found then
    raise exception 'Order tidak ditemukan.';
  end if;

  if p_new_status not in ('washing','drying','ironing','packing','ready','completed') then
    raise exception 'Status tujuan tidak valid.';
  end if;

  -- Hanya boleh bergerak maju. Quick mode boleh melompat dari proses aktif langsung ke ready.
  if not (
    (v_order.status='received' and p_new_status='washing') or
    (v_order.status='washing' and p_new_status in ('drying','ready')) or
    (v_order.status='drying' and p_new_status in ('ironing','ready')) or
    (v_order.status='ironing' and p_new_status in ('packing','ready')) or
    (v_order.status='packing' and p_new_status='ready') or
    (v_order.status='ready' and p_new_status='completed')
  ) then
    raise exception 'Perubahan progres dari % ke % tidak diizinkan.', v_order.status, p_new_status;
  end if;

  update public.v100_orders
  set
    status = p_new_status,
    progress_last_at = v_changed_at,
    progress_last_by_name = v_actor_name,
    progress_last_by_login_id = v_actor_login,
    updated_at = v_changed_at
  where id = p_order_id;

  insert into public.v113063_order_progress_history(
    order_id, order_no, old_status, new_status,
    actor_auth_uid, actor_employee_id, actor_name, actor_login_id, created_at
  ) values (
    v_order.id, v_order.order_no, v_order.status, p_new_status,
    auth.uid(), v_employee_id, v_actor_name, v_actor_login, v_changed_at
  );

  return query
  select true, v_order.status, p_new_status, v_actor_name, v_changed_at;
end;
$$;

grant execute on function public.v113063_update_order_progress(uuid,text) to authenticated;

-- View utama aplikasi: pertahankan semua kolom V113.0.61 + informasi progres terakhir.
create or replace view public.v100_orders_view
with (security_invoker = true)
as
select
  o.id,
  o.order_no,
  o.customer_id,
  c.name as customer_name,
  c.phone as customer_phone,
  o.status,
  o.payment_status,
  o.subtotal,
  o.discount,
  o.total,
  o.paid_amount,
  o.notes,
  o.due_at,
  o.created_at,
  o.created_by_name,
  o.created_by_login_id,
  o.progress_last_at,
  o.progress_last_by_name,
  o.progress_last_by_login_id
from public.v100_orders o
join public.v100_customers c on c.id = o.customer_id;

grant select on public.v100_orders_view to authenticated;
grant select on public.v113063_order_progress_history to authenticated;

notify pgrst, 'reload schema';

commit;
